version: "3.6"
services:
  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: P0stGre5Q1
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    networks:
      - adireto_network
  graphql-engine:
    image: hasura/graphql-engine:v1.1.0
    container_name: hasura
    # ports:
    #  - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:P0stGre5Q1@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: Ad1R3to
    networks:
      - adireto_network
    command:
      - graphql-engine
      - serve
  hasura-nginx:
    image: nginx
    container_name: hasura-nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - adireto_network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - graphql-engine
volumes:
  postgresqldata:
    driver: local
networks:
  adireto_network:
    driver: bridge
