version: '3.6'

services:
  caddy:
    image: caddy/caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - ./certbot/conf:/etc/letsencrypt

  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - /etc/letsencrypt/live/postgres.moneyexpense.my.id/:/var/lib/postgresql/certs/
      - ./config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    environment:
      POSTGRES_PASSWORD: postgrespassword222
      POSTGRES_SSL_MODE: verify-full
      POSTGRES_SSL_CERT: /var/lib/postgresql/certs/fullchain.pem
      POSTGRES_SSL_KEY: /var/lib/postgresql/certs/privkey.pem
    command: >
      -c ssl=on 
      -c ssl_cert_file=/var/lib/postgresql/certs/fullchain.pem
      -c ssl_key_file=/var/lib/postgresql/certs/privkey.pem

  graphql-engine:
    image: hasura/graphql-engine:v2.33.0
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword222@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: untumukui2323@
      HASURA_GRAPHQL_AUTH_HOOK: https://moneyexpense.my.id/hasura-webhook
      HASURA_GRAPHQL_AUTH_HOOK_MODE: GET
      HASURA_GRAPHQL_CORS_DOMAIN: "*"

volumes:
  caddy_data:

networks:
  custom_network:
    external: true
