version: '3.6'

services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./ssl:/etc/postgresql/ssl
    environment:
      POSTGRES_PASSWORD: postgrespassword2222
      POSTGRES_DB: dbMonney23 # Replace with your database name
      POSTGRES_USER: Untumu2 # Replace with your database user
    command: ["postgres", "-c", "ssl=on", "-c", "ssl_cert_file=/etc/postgresql/ssl/server.crt", "-c", "ssl_key_file=/etc/postgresql/ssl/server.key"]

  graphql-engine:
    image: hasura/graphql-engine:v2.33.0
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://Untumu2:postgrespassword2222@postgres:5432/dbMonney23
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_ADMIN_SECRET: your_admin_secret # Replace with your admin secret
      HASURA_GRAPHQL_AUTH_HOOK: https://moneysmatrexpense.vercel.app # Your authentication webhook URL
      HASURA_GRAPHQL_AUTH_HOOK_MODE: GET
      HASURA_GRAPHQL_CORS_DOMAIN: "*" # Allow all CORS domains
    command:
      - graphql-engine
      - serve
    cap_add:
      - IPC_LOCK
    tmpfs:
      - /tmp

  caddy:
    image: caddy/caddy
    depends_on:
      - "graphql-engine"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_certs:/root/.caddy
      - ./ssl:/etc/caddy/ssl
    networks:
      - default

volumes:
  db_data:
  caddy_certs:

networks:
  default:
    external:
      name: bridge
