version: '3.6'

services:
  traefik:
    image: traefik
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=your.email@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/acme.json"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
    networks:
      - web

  postgres:
    image: postgres:15
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: untumukui
      POSTGRES_DB: postgres
      PGSSLMODE: require
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postgres.rule=Host(`auth.smartmoney.bisnisnetz.com`)"
      - "traefik.http.routers.postgres.entrypoints=websecure"
      - "traefik.http.services.postgres.loadbalancer.server.port=5432"

  graphql-engine:
    image: hasura/graphql-engine:v2.33.0
    restart: always
    environment:
      HASURA_GRAPHQL_AUTH_HOOK: https://moneysmatrexpense.vercel.app
      HASURA_GRAPHQL_AUTH_HOOK_MODE: GET
      HASURA_GRAPHQL_CORS_DOMAIN: "*"
      HASURA_GRAPHQL_DATABASE_URL: postgres://your_username:your_password@postgres:5432/your_database_name
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ACCESS_KEY: untumukui
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hasura.rule=Host(`graphql.smartmoney.bisnisnetz.com`)"
      - "traefik.http.routers.hasura.entrypoints=websecure"
      - "traefik.http.services.hasura.loadbalancer.server.port=8080"

networks:
  web:
    external: true
    name: traefik_webgateway

volumes:
  db_data:
    external: true
